- name: Create the database's
  mysql_db: 
    login_user: root
    login_password: '{{ mysql_root_password }}'
    name: '{{ item }}'
    state: present
    # 一定要用utf8
    encoding: utf8
  with_items:
    - '{{ mysql_db_name }}'
  when: mysql_db_name|lower() != 'none'

- name: Create the database users
  mysql_user:
    login_user: root
    login_password: '{{ mysql_root_password }}' 
    name: '{{ item.name }}'
    password: '{{ item.pass|default("123456") }}'
    priv: '{{ item.priv|default("*.*:ALL") }}' 
    state: present
    host: '{{ item.host | default("localhost") }}'
  with_items:
    - "{{ mysql_users }}"
  when: mysql_users|lower() != 'none'