---

- name: check selinux has enabled
  command: getenforce
  register: has_selinux


- name: Set selinux context
  command: '{{ item }}'
  with_items:
     - chcon -R -u system_u /usr/share/nginx/html/static
     - chcon -R -t usr_t /usr/share/nginx/html/static
     - chcon -R -u system_u /usr/share/nginx/html/media
     - chcon -R -t usr_t /usr/share/nginx/html/media
  when: has_selinux.stdout=='Enforcing'